name: Build and Test

on: 
  push: 
    branches:
      - staging
  pull_request:
    branches:
      - staging

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code 
        uses: actions/checkout@v2
      - name: Set up NodeJS Environment
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm install
      - name: Run 
        run: npm run build